apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: 4

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
      - name: flask
        image: 893410593871.dkr.ecr.ap-south-1.amazonaws.com/employee-management:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
